Create homework8
KateSaulkina/Homeworks pull request #6
Opened 2019-12-22 18:01 UTC by KateSaulkina

2020-02-11 20:27 UTC, Maksim-Zhuravlev requested changes

2020-02-11 20:27 UTC, Maksim-Zhuravlev commented on sorts.c
> +        if (el == 0) {
- Отступ
- Если резервируете место под максимальный размер заранее, то поддерживаемее было бы вместо константы использовать последний элемент массива размеров, перенеся вычисление его размера выше.
- NULL лучше воспринимается

2020-02-11 20:27 UTC, Maksim-Zhuravlev commented on sorts.c
> +	char *name[]= {"countingSort", "quickSort", "bubbleSort"};
- Отступ
- Пробел

2020-02-11 20:27 UTC, Maksim-Zhuravlev commented on sorts.c
> +    if (l == r || l == (r - 1))
Фигурные скобки и отступ

2020-02-11 20:27 UTC, Maksim-Zhuravlev commented on sorts.c
> +		if (arr[k] > arr[k - 1]) {
Проверьте, что сортиовка работает. Есть подозрение, что после её выполнения массив не отсортирован.
В алгоритме быстрой сортировки сравнения просходят с одним и тем же элементом в пределах одного вызова. В представленном коде pivot не зафиксирован.
Данные по времени работы в таблице укрепляют сомнения.  При переходе от 9-ой строки к 10-й время работы увеличивается в 800 раз, а должно на порядок меньше.

2020-02-11 20:27 UTC, Maksim-Zhuravlev commented on sortStr.c
> +int Strcmp(void* point1, void* point2) {
strcmp сравнивает до первого несовпадения или до 0.
В файле строки разделены переносами (\n).
Если будут одинаковые строки, то \n будет "проскочен" и будут сравниваться символы следующих строк.
Поскольку я уже многим зачел задачу с такой ошибкой, то не исправляйте.
Отпишите, что прочитали и поняли, в чём возможная проблема.

2020-02-11 20:27 UTC, Maksim-Zhuravlev commented on sortStr.c
> +	fstat(fInp, &inf);
Отступ

2020-02-13 19:42 UTC, KateSaulkina commented on sortStr.c
> +int Strcmp(void* point1, void* point2) {
Спасибо, поняла

2020-02-15 13:03 UTC, KateSaulkina commented on sorts.c
> +		if (arr[k] > arr[k - 1]) {
Сортировка работает, время меняется в 84 раза

2020-02-15 13:09 UTC, KateSaulkina commented on sorts.c
> +		if (arr[k] > arr[k - 1]) {
Сортировка работает, время меняется в 84 раза

2020-03-01 14:35 UTC, merged